// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJRY133_2fTn4gKK1oYgPahSPPOgPSr0',
    appId: '1:216046358353:web:e5697cff3417e4dae20d70',
    messagingSenderId: '216046358353',
    projectId: 'catatankuliah-5721c',
    authDomain: 'catatankuliah-5721c.firebaseapp.com',
    databaseURL: 'https://catatankuliah-5721c-default-rtdb.firebaseio.com',
    storageBucket: 'catatankuliah-5721c.firebasestorage.app',
    measurementId: 'G-SFDSE2LRQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvhcs4XzOIqUlPwUnOnoI8s1Dp3QVffU',
    appId: '1:216046358353:android:d1723fbe7510a057e20d70',
    messagingSenderId: '216046358353',
    projectId: 'catatankuliah-5721c',
    databaseURL: 'https://catatankuliah-5721c-default-rtdb.firebaseio.com',
    storageBucket: 'catatankuliah-5721c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipEmTU2g3Av1x5-vY2CkFx1VxeYR37KU',
    appId: '1:216046358353:ios:3c5bb59f8596d8d4e20d70',
    messagingSenderId: '216046358353',
    projectId: 'catatankuliah-5721c',
    databaseURL: 'https://catatankuliah-5721c-default-rtdb.firebaseio.com',
    storageBucket: 'catatankuliah-5721c.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipEmTU2g3Av1x5-vY2CkFx1VxeYR37KU',
    appId: '1:216046358353:ios:3c5bb59f8596d8d4e20d70',
    messagingSenderId: '216046358353',
    projectId: 'catatankuliah-5721c',
    databaseURL: 'https://catatankuliah-5721c-default-rtdb.firebaseio.com',
    storageBucket: 'catatankuliah-5721c.firebasestorage.app',
    iosBundleId: 'com.example.catatanKuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKJRY133_2fTn4gKK1oYgPahSPPOgPSr0',
    appId: '1:216046358353:web:c6f027a98718591fe20d70',
    messagingSenderId: '216046358353',
    projectId: 'catatankuliah-5721c',
    authDomain: 'catatankuliah-5721c.firebaseapp.com',
    databaseURL: 'https://catatankuliah-5721c-default-rtdb.firebaseio.com',
    storageBucket: 'catatankuliah-5721c.firebasestorage.app',
    measurementId: 'G-WBFPH3MWE2',
  );
}
